In [1]:
import openpyxl
import os
import pandas as pd
from openpyxl import load_workbook
import numpy

In [2]:
daily_totals = pd.read_excel ('SALES LOG - XYZ COMPANY.xlsx')

In [3]:
main_total = pd.read_excel ('tabula-END OF DAY REPORT - XYZ COMPANY.xlsx', header=3)

In [4]:
main_total

,PO #,CUSTOMER ID,DATE OF SALERECEIPT #,AMOUNT,SPEED TYPE
0,81730,NaN,NaN,NaN,NaN
1,81730,126104,03/13/2020 0001492287,40,G0401A
2,81730,139729,03/12/2020 0001492286,50,G0419A
3,81730,415802,03/14/2020 0001492281,100,G0598A
4,81730,1018908,03/12/2020 0001492288,20,G3035A
5,81730,1065569,03/05/2020 0001492289,1500,G2477A
6,NaN,NaN,NaN,1710,NaN
7,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN
9,81733,129188,03/13/2020 0001492256,150,A0176
10,81733,141077,03/13/2020 0001492248,25000,A0116
11,81733,149443,03/11/2020 0001492251,2000,A0168
12,81733,163549,03/12/2020 0001492260,1600,A8008
13,81733,302068,03/14/2020 0001492277,200,A0108
14,81733,318123,03/11/2020 0001492255,444,A8008
15,81733,413376,03/11/2020 0001492265,3200,A8008
16,81733,413376,03/13/2020 0001492270,200,A8008
17,81733,424431,03/10/2020 0001492249,1000,A0168
18,81733,432540,03/10/2020 0001492264,7900,A8008
19,81733,432540,03/20/2020 0001492295,100,A8008
20,81733,810469,03/14/2020 0001492278,800,A0108
21,81733,824824,03/09/2020 0001492247,25000,A0063
22,81733,834696,03/11/2020 0001492261,3200,A8008
23,81733,837873,03/10/2020 0001492250,714.5,A0168
24,81733,867566,03/13/2020 0001492267,20,A0018
25,81733,873349,03/10/2020 0001492268,3200,A8008
26,81733,877756,03/10/2020 0001492252,1000,A0168
27,81733,907172,03/09/2020 0001492272,268750,A5737
28,81733,907172,03/09/2020 0001492274,100000,A8005
29,81733,914864,03/11/2020 0001492254,1000,A0168
30,81733,916980,03/11/2020 0001492266,1200,A8008
31,81733,936797,03/10/2020 0001492253,457.28,A0168
32,81733,976785,03/12/2020 0001492275,10000,A0010
33,81733,976785,03/12/2020 0001492276,1400,A0108
34,81733,993472,03/13/2020 0001492245,35,A0176
35,81733,1001448,03/11/2020 0001492269,1200,A8008
36,81733,1002032,03/14/2020 0001492257,1200,A8008
37,81733,1025858,03/11/2020 0001492262,40,A8008
38,81733,1035053,03/13/2020 0001492259,1200,A8008
39,81733,1035701,03/10/2020 0001492263,2400,A8008
40,81733,1035704,03/09/2020 0001492258,1200,A8008
41,81733,1039113,03/11/2020 0001492271,100,A8008
42,81733,1043815,03/10/2020 0001492246,100,A0010
43,81733,1054901,03/13/2020 0001492273,15,AWBBL
44,NaN,NaN,NaN,466026,NaN
45,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,XYZ COMPANY,NaN,NaN
48,NaN,NaN,END OF DAY REPORT,NaN,NaN
49,NaN,NaN,2020-03-20 00:00:00,NaN,NaN
50,PO #,CUSTOMER ID,DATE OF SALERECEIPT #,AMOUNT SPEEDTYPE,NaN
51,81736,164304,03/14/2020 0001492293,$50.00 G0400A,NaN
52,81736,164304,03/14/2020 0001492294,$50.00 G1802A,NaN
53,81736,820366,03/13/2020 0001492290,$45.00 G0400A,NaN
54,81736,828968,03/15/2020 0001492291,$50.00 G1385A,NaN
55,81736,134593,03/16/2020 0001492292,$250.00 G1651A,NaN
56,NaN,NaN,NaN,445,NaN
57,NaN,NaN,NaN,"GRAND TOTAL: $468,180.78",NaN

In [5]:
daily_totals

,SALES ID,DEPOSIT DATE,TENDER TYPE,SALES TYPE,PO #,DATE OF SALE,TAX RCPT,SPECIAL,SALE AMT,TAX EXEMPT AMT,...,ATH CAP,ATH AC CU,ATH RESTRICTRED,RESTRICTED PD,CURRENT USE PD,ATH CU PD,ATH CAP PD,ATH CU PD.1,ATH RESTRICTED PD,ADJ
0,1,2020-02-26 00:00:00,CK,Check,81551,2020-03-02,19,1,1090.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020-02-27 00:00:00,CK,Check,81563,2020-03-02,5,NaN,6578.84,1300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2020-02-27 00:00:00,CK,Check,81564,2020-03-02,0,1,200.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2020-02-27 00:00:00,CK,Check,81565,2020-03-02,10,0,1700.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020-02-27 00:00:00,CK,Check,81566,2020-03-02,8,0,3675.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Get the grand total from sales log
daily_grand_total = daily_totals.loc[daily_totals['TOTAL '].str.contains('GRAND TOTAL', na=False, case=False), 'QUOTE AMT']

In [7]:
# Get the grand total from the end of day report
main_grand_total = main_total.loc[main_total['AMOUNT'].str.contains('GRAND TOTAL', na=False), 'AMOUNT'].str.split('$').str[1].str.replace(',', '').astype(float).values[0]

In [8]:
main_total

,PO #,CUSTOMER ID,DATE OF SALERECEIPT #,AMOUNT,SPEED TYPE
0,81730,NaN,NaN,NaN,NaN
1,81730,126104,03/13/2020 0001492287,40,G0401A
2,81730,139729,03/12/2020 0001492286,50,G0419A
3,81730,415802,03/14/2020 0001492281,100,G0598A
4,81730,1018908,03/12/2020 0001492288,20,G3035A
5,81730,1065569,03/05/2020 0001492289,1500,G2477A
6,NaN,NaN,NaN,1710,NaN
7,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN
9,81733,129188,03/13/2020 0001492256,150,A0176
10,81733,141077,03/13/2020 0001492248,25000,A0116
11,81733,149443,03/11/2020 0001492251,2000,A0168
12,81733,163549,03/12/2020 0001492260,1600,A8008
13,81733,302068,03/14/2020 0001492277,200,A0108
14,81733,318123,03/11/2020 0001492255,444,A8008
15,81733,413376,03/11/2020 0001492265,3200,A8008
16,81733,413376,03/13/2020 0001492270,200,A8008
17,81733,424431,03/10/2020 0001492249,1000,A0168
18,81733,432540,03/10/2020 0001492264,7900,A8008
19,81733,432540,03/20/2020 0001492295,100,A8008
20,81733,810469,03/14/2020 0001492278,800,A0108
21,81733,824824,03/09/2020 0001492247,25000,A0063
22,81733,834696,03/11/2020 0001492261,3200,A8008
23,81733,837873,03/10/2020 0001492250,714.5,A0168
24,81733,867566,03/13/2020 0001492267,20,A0018
25,81733,873349,03/10/2020 0001492268,3200,A8008
26,81733,877756,03/10/2020 0001492252,1000,A0168
27,81733,907172,03/09/2020 0001492272,268750,A5737
28,81733,907172,03/09/2020 0001492274,100000,A8005
29,81733,914864,03/11/2020 0001492254,1000,A0168
30,81733,916980,03/11/2020 0001492266,1200,A8008
31,81733,936797,03/10/2020 0001492253,457.28,A0168
32,81733,976785,03/12/2020 0001492275,10000,A0010
33,81733,976785,03/12/2020 0001492276,1400,A0108
34,81733,993472,03/13/2020 0001492245,35,A0176
35,81733,1001448,03/11/2020 0001492269,1200,A8008
36,81733,1002032,03/14/2020 0001492257,1200,A8008
37,81733,1025858,03/11/2020 0001492262,40,A8008
38,81733,1035053,03/13/2020 0001492259,1200,A8008
39,81733,1035701,03/10/2020 0001492263,2400,A8008
40,81733,1035704,03/09/2020 0001492258,1200,A8008
41,81733,1039113,03/11/2020 0001492271,100,A8008
42,81733,1043815,03/10/2020 0001492246,100,A0010
43,81733,1054901,03/13/2020 0001492273,15,AWBBL
44,NaN,NaN,NaN,466026,NaN
45,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,XYZ COMPANY,NaN,NaN
48,NaN,NaN,END OF DAY REPORT,NaN,NaN
49,NaN,NaN,2020-03-20 00:00:00,NaN,NaN
50,PO #,CUSTOMER ID,DATE OF SALERECEIPT #,AMOUNT SPEEDTYPE,NaN
51,81736,164304,03/14/2020 0001492293,$50.00 G0400A,NaN
52,81736,164304,03/14/2020 0001492294,$50.00 G1802A,NaN
53,81736,820366,03/13/2020 0001492290,$45.00 G0400A,NaN
54,81736,828968,03/15/2020 0001492291,$50.00 G1385A,NaN
55,81736,134593,03/16/2020 0001492292,$250.00 G1651A,NaN
56,NaN,NaN,NaN,445,NaN
57,NaN,NaN,NaN,"GRAND TOTAL: $468,180.78",NaN

In [9]:
# They happen to be equal for your example
daily_grand_total == main_grand_total

161    True
Name: QUOTE AMT, dtype: bool

In [10]:
main_total

,PO #,CUSTOMER ID,DATE OF SALERECEIPT #,AMOUNT,SPEED TYPE
0,81730,NaN,NaN,NaN,NaN
1,81730,126104,03/13/2020 0001492287,40,G0401A
2,81730,139729,03/12/2020 0001492286,50,G0419A
3,81730,415802,03/14/2020 0001492281,100,G0598A
4,81730,1018908,03/12/2020 0001492288,20,G3035A
5,81730,1065569,03/05/2020 0001492289,1500,G2477A
6,NaN,NaN,NaN,1710,NaN
7,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN
9,81733,129188,03/13/2020 0001492256,150,A0176
10,81733,141077,03/13/2020 0001492248,25000,A0116
11,81733,149443,03/11/2020 0001492251,2000,A0168
12,81733,163549,03/12/2020 0001492260,1600,A8008
13,81733,302068,03/14/2020 0001492277,200,A0108
14,81733,318123,03/11/2020 0001492255,444,A8008
15,81733,413376,03/11/2020 0001492265,3200,A8008
16,81733,413376,03/13/2020 0001492270,200,A8008
17,81733,424431,03/10/2020 0001492249,1000,A0168
18,81733,432540,03/10/2020 0001492264,7900,A8008
19,81733,432540,03/20/2020 0001492295,100,A8008
20,81733,810469,03/14/2020 0001492278,800,A0108
21,81733,824824,03/09/2020 0001492247,25000,A0063
22,81733,834696,03/11/2020 0001492261,3200,A8008
23,81733,837873,03/10/2020 0001492250,714.5,A0168
24,81733,867566,03/13/2020 0001492267,20,A0018
25,81733,873349,03/10/2020 0001492268,3200,A8008
26,81733,877756,03/10/2020 0001492252,1000,A0168
27,81733,907172,03/09/2020 0001492272,268750,A5737
28,81733,907172,03/09/2020 0001492274,100000,A8005
29,81733,914864,03/11/2020 0001492254,1000,A0168
30,81733,916980,03/11/2020 0001492266,1200,A8008
31,81733,936797,03/10/2020 0001492253,457.28,A0168
32,81733,976785,03/12/2020 0001492275,10000,A0010
33,81733,976785,03/12/2020 0001492276,1400,A0108
34,81733,993472,03/13/2020 0001492245,35,A0176
35,81733,1001448,03/11/2020 0001492269,1200,A8008
36,81733,1002032,03/14/2020 0001492257,1200,A8008
37,81733,1025858,03/11/2020 0001492262,40,A8008
38,81733,1035053,03/13/2020 0001492259,1200,A8008
39,81733,1035701,03/10/2020 0001492263,2400,A8008
40,81733,1035704,03/09/2020 0001492258,1200,A8008
41,81733,1039113,03/11/2020 0001492271,100,A8008
42,81733,1043815,03/10/2020 0001492246,100,A0010
43,81733,1054901,03/13/2020 0001492273,15,AWBBL
44,NaN,NaN,NaN,466026,NaN
45,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,XYZ COMPANY,NaN,NaN
48,NaN,NaN,END OF DAY REPORT,NaN,NaN
49,NaN,NaN,2020-03-20 00:00:00,NaN,NaN
50,PO #,CUSTOMER ID,DATE OF SALERECEIPT #,AMOUNT SPEEDTYPE,NaN
51,81736,164304,03/14/2020 0001492293,$50.00 G0400A,NaN
52,81736,164304,03/14/2020 0001492294,$50.00 G1802A,NaN
53,81736,820366,03/13/2020 0001492290,$45.00 G0400A,NaN
54,81736,828968,03/15/2020 0001492291,$50.00 G1385A,NaN
55,81736,134593,03/16/2020 0001492292,$250.00 G1651A,NaN
56,NaN,NaN,NaN,445,NaN
57,NaN,NaN,NaN,"GRAND TOTAL: $468,180.78",NaN

In [11]:
# Forward fill blank POs
main_total['PO #'] = main_total['PO #'].ffill()

In [12]:
# Filter out NAs
main_total = main_total.loc[~main_total['AMOUNT'].isna()].copy()

In [13]:
main_total.columns

Index(['PO #', 'CUSTOMER ID', 'DATE OF SALERECEIPT #', 'AMOUNT', 'SPEED TYPE'], dtype='object')

In [14]:
# Fill subtotal NAs
main_total.loc[main_total['CUSTOMER ID'].isna(), 'CUSTOMER ID'] = 'Subtotal'
main_total.loc[main_total['CUSTOMER ID'].isna(), 'DATE OF SALERECEIPT #'] = 'Subtotal'
main_total.loc[main_total['CUSTOMER ID'].isna(), 'SPEED TYPE'] = 'Subtotal'

In [15]:
# Filter the messy daily totals with the cleaner POs
totals_filter = main_total['PO #'].unique()

In [16]:
# Use numbers only
totals_filter = [i for i in totals_filter if isinstance(i, int) is True]

In [17]:
main_total.columns

Index(['PO #', 'CUSTOMER ID', 'DATE OF SALERECEIPT #', 'AMOUNT', 'SPEED TYPE'], dtype='object')

In [18]:
# View the main totals again with the filter
main_total_viz = main_total.loc[main_total['PO #'].isin(totals_filter)][:40].copy()
main_total_viz['AMOUNT'] = main_total_viz['AMOUNT'].astype(float)
main_total_viz.loc[main_total_viz['PO #'].isin(totals_filter)].style.bar(subset=['AMOUNT'], align='mid', color=['#d65f5f', '#5fba7d']).highlight_null(null_color='red')

In [19]:
# View the PO Breakdown
daily_totals.loc[daily_totals['PO #'].isin(totals_filter)].style.bar(subset=['SALE AMT', 'TOTAL '], align='mid', color=['#d65f5f', '#5fba7d']).highlight_null(null_color='red')

In [20]:
# View the other total once more
main_grand_total

468180.78

In [21]:
# I think this is what we want
daily_totals.loc[daily_totals['PO #'].isin(totals_filter), 'SALE AMT'].sum()

468180.78